// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lyon1agendaclient/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AgendaAdapter());
    registerAdapter(DayAdapter());
    registerAdapter(EventAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AgendaAdapter());
    registerAdapter(DayAdapter());
    registerAdapter(EventAdapter());
  }
}
