name: onyx_workspace

packages:
  - packages/*
  - apps/*

scripts:
  analyze:
    exec: dart analyze .
  formatting:check: melos exec -- dart format --set-exit-if-changed .

  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  test:
    run: melos exec --no-flutter dart test