name: onyx_workspace

packages:
  - packages/*
  - apps/*

scripts:
  analyze:
    exec: dart analyze .
  formatting:check: melos exec -- dart format --set-exit-if-changed .

  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Flutter packages in this project.

  test:
    run: melos exec --no-flutter dart test

  format: melos exec -- dart format .