// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:polytechcolloscopeclient/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(KholleAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(StudentColloscopeAdapter());
    registerAdapter(YearAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(KholleAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(StudentColloscopeAdapter());
    registerAdapter(YearAdapter());
  }
}
