// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:izlyclient/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CrousTypeAdapter());
    registerAdapter(IzlyCredentialAdapter());
    registerAdapter(IzlyPaymentModelAdapter());
    registerAdapter(IzlyPaymentModelListAdapter());
    registerAdapter(IzlyQrCodeAdapter());
    registerAdapter(IzlyQrCodeListAdapter());
    registerAdapter(MenuCrousAdapter());
    registerAdapter(MenuTypeAdapter());
    registerAdapter(PlatCrousAdapter());
    registerAdapter(RestaurantListModelAdapter());
    registerAdapter(RestaurantModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CrousTypeAdapter());
    registerAdapter(IzlyCredentialAdapter());
    registerAdapter(IzlyPaymentModelAdapter());
    registerAdapter(IzlyPaymentModelListAdapter());
    registerAdapter(IzlyQrCodeAdapter());
    registerAdapter(IzlyQrCodeListAdapter());
    registerAdapter(MenuCrousAdapter());
    registerAdapter(MenuTypeAdapter());
    registerAdapter(PlatCrousAdapter());
    registerAdapter(RestaurantListModelAdapter());
    registerAdapter(RestaurantModelAdapter());
  }
}
