// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lyon1mailclient/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActionAdapter());
    registerAdapter(ActionListAdapter());
    registerAdapter(ActionTypeAdapter());
    registerAdapter(MailAdapter());
    registerAdapter(MailBoxAdapter());
    registerAdapter(MailBoxListAdapter());
    registerAdapter(SpecialMailBoxAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActionAdapter());
    registerAdapter(ActionListAdapter());
    registerAdapter(ActionTypeAdapter());
    registerAdapter(MailAdapter());
    registerAdapter(MailBoxAdapter());
    registerAdapter(MailBoxListAdapter());
    registerAdapter(SpecialMailBoxAdapter());
  }
}
