// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lyon1tomussclient/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EnumerationAdapter());
    registerAdapter(GradeAdapter());
    registerAdapter(PresenceAdapter());
    registerAdapter(PresenceColorAdapter());
    registerAdapter(SemesterAdapter());
    registerAdapter(SemesterListAdapter());
    registerAdapter(StageCodeAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(TeachingUnitAdapter());
    registerAdapter(TeachingUnitListAdapter());
    registerAdapter(TomussTextAdapter());
    registerAdapter(URLAdapter());
    registerAdapter(UploadAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EnumerationAdapter());
    registerAdapter(GradeAdapter());
    registerAdapter(PresenceAdapter());
    registerAdapter(PresenceColorAdapter());
    registerAdapter(SemesterAdapter());
    registerAdapter(SemesterListAdapter());
    registerAdapter(StageCodeAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(TeachingUnitAdapter());
    registerAdapter(TeachingUnitListAdapter());
    registerAdapter(TomussTextAdapter());
    registerAdapter(URLAdapter());
    registerAdapter(UploadAdapter());
  }
}
