targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart': [ 'lib/{{path}}/generated/{{file}}.mapper.dart', 'lib/{{path}}/generated/{{file}}.init.dart' ]
global_options:
  dart_mappable_builder:
    options:
      renameMethods:
        fromJson: deserialize
        toJson: serialize
        fromMap: fromJson
        toMap: toJson