name: polytechcolloscopeclient
description: a library aiming at providing a simple interface to fetch data from Polytech Lyon Colloscope
version: 1.0.11
repository: https://github.com/onyx-lyon1/onyx/tree/main/packages/polytechcolloscopeclient

environment:
  sdk: ">=3.8.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  collection: ^1.17.2
  dotenv: ^4.2.0
  html: ^0.15.4
  requests_plus: ^4.8.4
  diacritic: ^0.1.5
  dart_mappable: ^4.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
  build_runner: ^2.2.0
  dart_mappable_builder: ^4.6.0
