name: polytechcolloscopeclient
description: a library aiming at providing a simple interface to fetch data from Polytech Lyon Colloscope
version: 1.0.11
repository: https://github.com/onyx-lyon1/onyx/tree/main/packages/polytechcolloscopeclient

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  collection: ^1.17.2
  dotenv: ^4.2.0
  equatable: ^2.0.5
  hive: ^2.2.3
  copy_with_extension: ^6.0.1
  html: ^0.15.4
  requests_plus: ^4.8.4
  diacritic: ^0.1.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0
  build_runner: ^2.2.0
  hive_generator: ^2.0.0
  copy_with_extension_gen: ^6.0.0
