// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_exec_token`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Lyon1CasClient>>
abstract class Lyon1CasClient implements RustOpaqueInterface {
  Future<bool> authenticateUser(
      {required String username, required String password});

  bool authenticated();

  Future<bool> logout();

  factory Lyon1CasClient() => RustLib.instance.api.crateCasLyon1CasClientNew();

  Future<String> serviceRequest(
      {required String service, required bool unsafeReq, required bool wrap});
}
