// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:onyx/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FunctionalitiesAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(ThemeModeEnumAdapter());
    registerAdapter(ThemeSettingsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FunctionalitiesAdapter());
    registerAdapter(SettingsModelAdapter());
    registerAdapter(ThemeModeEnumAdapter());
    registerAdapter(ThemeSettingsModelAdapter());
  }
}
