targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            "lib/{{path}}/{{file}}.dart": "lib/{{path}}/{{file}}.g.dart"
