name: Android

on:
  pull_request:
    branches:
      - main

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.2'

    - name: Prepare
      working-directory: apps/onyx
      run: flutter pub get

    - name: Build APK
      working-directory: apps/onyx
      run: flutter build apk --profile

    - name: Build App Bundle
      working-directory: apps/onyx
      run: flutter build appbundle --profile
