name: Android

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2.11.0
      with:
        channel: 'stable'

    - name: Prepare
      working-directory: apps/onyx
      run: flutter pub get

    - name: Build APK
      working-directory: apps/onyx
      run: flutter build apk --profile --no-tree-shake-icons

    - name: Build App Bundle
      working-directory: apps/onyx
      run: flutter build appbundle --profile --no-tree-shake-icons
