name: iOS

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.11.0
      with:
        channel: 'stable'
        architecture: x64

    - name: Prepare
      working-directory: apps/onyx
      run: flutter pub get
    
    - name: Build
      working-directory: apps/onyx
      run: flutter build ios --release --no-codesign --no-tree-shake-icons
